# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on: [push, pull_request]

jobs:
  build_and_upload:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: npm install, build, and test
      run: |
        yarn --frozen-lockfile
        yarn build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          dist

